# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :distribute do
    sh "cd ../.. && flutter build ipa --release"
    ipa_path = File.expand_path("../../build/ios/ipa/Runner.ipa", __dir__)

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      service_credentials_file: "fastlane/service-account.json",
      ipa_path: ipa_path,
      groups: "internal-testers",
      release_notes: "Build tự động từ CI/CD"
    )
  end
  
end
