# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build và upload lên Firebase"
  lane :distribute do
    # Build Flutter APK
    sh "cd ../.. && flutter build apk --release"

    sh("pwd")

    sh("ls -R ../build/app/outputs/flutter-apk")
    # Upload lên Firebase App Distribution
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"],
      service_credentials_file: "fastlane/service-account.json",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: "internal-testers",
      release_notes: "Build tự động từ CI/CD"
    )
  end
  
end
